### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by itjunkii83** [ooper-shlab/RosyWriter2.1-Swift#2]
This magical wizardry of a port has been a hugely valuable learning tool. Thank you for putting this together, I struggle with the documentation when dealing with AVCapture like this - your code has been so helpful 

Is there any chance you could guide me on how I would use the OpenGL renderer to write text on each CVPixelBuffer? I want to make a video timer as my end goal. I have it working with CIFilter Image Composite but the performance hit of drawing the UIImage of a UILabel is making it look like a not ideal solution - if I could purely use OpenGL I am hoping I could get better performance.

**Comment by ooper-shlab** [comment]
Sorry for leaving your post for such a long time. Maybe I opened this post when I was very busy and have been forgotten... Anyway I have just translated this sample code and not good at OpenGL rendering. I hope you find a good way to do what you want (or already found?). Good luck.
